#!/usr/bin/env bash

THIS=$(basename $0)

HELP="
Usage: ${THIS} [COMMAND] [OPTION]...

Set of commands for interacting with Abaco API. Options vary by 
command; use -h flag after command to view usage details.

Commands:
  list, ls, actors, images	list actors
  create, make, register        create new actor
  delete, remove, rm            remove actor
  workers, worker               view and add workers
  submit, run                   run actor
  executions                    view actor executions
  logs				view execution logs
"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

case "$1" in
  list|ls|actors|images)	shift;
	$DIR/abaco-list.sh "$@";;

  create|make|register)       	shift;
	$DIR/abaco-create.sh "$@";;

  delete|remove|rm)    		shift;
	$DIR/abaco-delete.sh "$@";;		

  workers|worker)		shift;
	$DIR/abaco-workers.sh "$@";;

  submit|run)			shift;
	$DIR/abaco-submit.sh "$@";;

  executions)                   shift;
        $DIR/abaco-executions.sh "$@";;

  logs)                         shift;
        $DIR/abaco-logs.sh "$@";;

  *) 				shift;
	echo "$HELP"; exit 0;;
esac
