#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

case "$1" in
  list|ls|actors|images)      shift;
    $DIR/abaco-list.sh "$@";;

  logs)         shift;
    $DIR/abaco-logs.sh "$@";;

  executions)   shift;
    $DIR/abaco-executions.sh "$@";;

  create)       shift;
    $DIR/abaco-create.sh "$@";;

  delete)	    shift;
	$DIR/abaco-delete.sh "$@";;		

  foo)
        case $1 in
            cp|copy)        shift; vdj-files-copy.py "$@";;
            dl|download)    shift; vdj-files-get.py "$@";;
            history)        shift; vdj-files-history.py "$@";;
            import)         shift; vdj-files-import.py "$@";;
            index)          shift; echo "Not currently implemented";;
            ls|list)        shift; vdj-files-list.py "$@";;
            mv|move)        shift; vdj-files-move.py "$@";;
            pems)           shift;
                    case $1 in
                        ls|list)      shift; files-pems-list.py "$@";;
                        rm|delete)    shift; files-pems-delete.py "$@";;
                        update)       shift; files-pems-update.py "$@";;
                    esac;;

            publish)        shift; echo "Not currently implemented";;
            rn|rename)      shift; vdj-files-rename.py "$@";;
            rm|delete)      shift; vdj-files-delete.py "$@";;
            ul|upload)      shift; vdj-files-upload.py "$@";;
            *)              vdj-files-list.py "$@";;
        esac;;

  jobs)     shift;
        case $1 in
            history)        shift; jobs-history.py "$@";;
            ls|list)        shift; jobs-list.py "$@";;
            out|output)     shift; echo "Not currently implemented";;
            pems)           shift;
                    case $1 in
                        ls|list)      shift; jobs-pems-list.py "$@";;
                        rm|delete)    shift; jobs-pems-delete.py "$@";;
                        update)       shift; jobs-pems-update.py "$@";;
                    esac;;

            resubmit)       shift; jobs-resubmit.py "$@";;
            rm|delete)      shift; jobs-delete.py "$@";;
            run)            shift; echo "Not currently implemented";;
            search)         shift; echo "Not currently implemented";;
            status)         shift; jobs-status.py "$@";;
            submit)         shift; jobs-submit.py "$@";;
            template)       shift; echo "Not currently implemented";;
            *)              jobs-list.py "$@";;
        esac;;

  login)    shift;
    case $1 in
        check)        shift; vdj-auth-check.py "$@";;
        create)        shift; vdj-login.py "$@";;
        refresh)        shift; vdj-login.py -r "$@";;
        *)            vdj-login.py "$@";;
    esac;;

  metadata) shift;
        case $1 in
            addupdate)      shift; metadata-addupdate.py "$@";;
            ls|list)        shift; metadata-list.py "$@";;
            pems)           shift;
                    case $1 in
                        ls|list)      shift; metadata-pems-list.py "$@";;
                        rm|delete)    shift; metadata-pems-delete.py "$@";;
                        update)       shift; metadata-pems-update.py "$@";;
                    esac;;

            schema)         shift; echo "Not currently implemented";;
            rm|remove)      shift; metadata-delete.py "$@";;
            *)              metadata-list.py "$@";;
        esac;;

  monitors) shift;
        case $1 in
            addupdate)      shift; monitors-add.py "$@";;
            checks)         shift; monitors-checks-list.py "$@";;
            ls|list)        shift; monitors-list.py "$@";;
            rm|delete)      shift; monitors-delete.py "$@";;
            *)              monitors-list.py "$@";;
        esac;;

  notifications)shift;
        case $1 in
            addupdate)      shift; notifications-addupdate.py "$@";;
            ls|list)        shift; notifications-list.py "$@";;
            rm|delete)      shift; notifications-delete.py "$@";;
            search)         shift; echo "Not currently implemented";;
            *)              notifications-list.py "$@";;
        esac;;

  profiles) shift; profiles-list.py "$@";;

  projects) shift;
        case $1 in
            create)         shift; echo "Project creation through CLI not yet added";;
            ls|list)        shift; vdj-projects-list.py "$@";;
            rm|delete)      shift; echo "Project deletion through CLI not yet added";;
            *)              vdj-projects-list.py "$@";;     
        esac;;

  postits)  shift;
        case $1 in
            create)         shift; postits-create.py "$@";;
            ls|list)        shift; postits-list.py "$@";;
            rm|delete)      shift; postits-delete.py "$@";;
            *)              postits-list.py "$@";;
        esac;;

  systems)  shift;
        case $1 in
            addupdate)      shift; systems-addupdate.py "$@";;
            clone)          shift; echo "Not currently implemented";;
            disable)        shift; systems-disable.py "$@";;
            enable)         shift; systems-enable.py "$@";;
            history)        shift; echo "Not currently implemented";;
            ls|list)        shift; systems-list.py "$@";;
            publish)        shift; systems-publish.py "$@";;
            queues)         shift; echo "Not currently implemented";;
            rm|delete)      shift; systems-delete.py "$@";;
            roles)           shift;
                    case $1 in
                        ls|list)      shift; systems-roles-list.py "$@";;
                        rm|delete)    shift; systems-roles-delete.py "$@";;
                        update)       shift; systems-roles-update.py "$@";;
                    esac;;

            search)         shift; echo "Not currently implemented";;
            setdefault)     shift; systems-setdefault.py "$@";;
            unpublish)      shift; systems-unpublish.py "$@";;
            unsetdefault)   shift; systems-unsetdefault.py "$@";;
            *)              systems-list.py "$@";;
        esac;;

  -h|--help|-help)      ;;
  --) ;;
  *) ;;
esac
